# Generated by Django 5.0.7 on 2024-12-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RetailSale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="sub_category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
