# Generated by Django 5.0.6 on 2024-11-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=25)),
                ('category_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_size', models.CharField(max_length=10)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('barcode_image', models.ImageField(upload_to='barcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=50)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
