# Generated by Django 5.0.6 on 2024-11-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Barcode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_size', models.CharField(max_length=10)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('barcode_image', models.ImageField(upload_to='barcodes/')),
            ],
        ),
    ]
