# Generated by Django 5.0.6 on 2024-11-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentShopAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='SubCategory_name',
            new_name='name',
        ),
    ]
