# Generated by Django 5.0.6 on 2024-11-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarmentShopAPI', '0002_rename_subcategory_name_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
