# Generated by Django 5.0.7 on 2024-10-08 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0003_item"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_code",
            new_name="catagory_code",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="category_name",
            new_name="catagory_name",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="category",
            new_name="catagory",
        ),
    ]
