# Generated by Django 5.0.7 on 2024-10-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0005_rename_category_catagory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("design_name", models.CharField(max_length=100)),
                ("design_code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "associated_items",
                    models.ManyToManyField(
                        related_name="designs", to="GarmentShopAPI.item"
                    ),
                ),
            ],
        ),
    ]
