# Generated by Django 5.0.7 on 2024-10-09 06:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0006_design"),
    ]

    operations = [
        migrations.AddField(
            model_name="catagory",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="design",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
