# Generated by Django 5.0.7 on 2024-10-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0007_catagory_created_at_company_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("party_name", models.CharField(max_length=255)),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("Vendor", "Vendor"),
                            ("Supplier", "Supplier"),
                            ("Customer", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gst_number", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
