# Generated by Django 5.0.7 on 2024-10-09 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0010_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
