# Generated by Django 5.0.7 on 2024-10-10 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0011_tax_created_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Catagory",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="catagory_code",
            new_name="category_code",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="catagory_name",
            new_name="category_name",
        ),
        migrations.RenameField(
            model_name="item",
            old_name="catagory",
            new_name="category",
        ),
    ]
