# Generated by Django 5.0.7 on 2024-10-14 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0013_financialyear"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialyear",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
