# Generated by Django 5.0.7 on 2024-10-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0014_financialyear_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="item",
            name="total_quantity_sold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="total_sales_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
