# Generated by Django 5.0.7 on 2024-10-14 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0015_item_cost_price_item_total_quantity_sold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="total_quantity_sold",
        ),
        migrations.RemoveField(
            model_name="item",
            name="total_sales_amount",
        ),
    ]
