# Generated by Django 5.0.7 on 2024-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "GarmentShopAPI",
            "0017_user_contact_number_user_description_user_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
