# Generated by Django 5.0.7 on 2024-10-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0018_alter_user_contact_number_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="category",
        ),
        migrations.AddField(
            model_name="item",
            name="category_item",
            field=models.CharField(default="default_category", max_length=255),
        ),
    ]
