# Generated by Django 5.0.7 on 2024-10-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0020_remove_design_associated_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="party_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
